version: '2'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "6960:5432"

  mongo:
    image: mongo
    ports:
      - "6961:27017"
