version: '2'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
  mongo:
    image: mongo
  sqlparser:
    image: sqlparser
    volumes:
      - .:/demo
    environment:
      - "SQLPARSER_PROMPTLOG=/demo/.sqlparserlog"
    depends_on:
      - postgres
      - mongo
